In [58]:
import pandas as pd
import torch
from torch import nn
from torch import sigmoid

In [95]:
#importing data from the set.
mnist_data = pd.read_csv('mnist_train.csv', dtype="float").dropna()

In [96]:
Y = torch.tensor(mnist_data['label']).float()
X_list = mnist_data.drop(columns=['label'])
X = torch.tensor(X_list.values).float()

In [98]:
# Creating the Neural Netowrk: 
# D_in-no. of inputs
# D_out- no. of outputs
# H- no of neurons in hidden layer
class CNN(nn.Module):
    def __init__(self,D_in, H, D_out):
        super(CNN,self).__init__()
        self.linear1 = nn.Linear(D_in, H)
        self.linear2 = nn.Linear(H,D_out)
        
    def forward(self,x):
        x = sigmoid(self.linear1(x))
        x = sigmoid(self.linear2(x))
        return x

In [126]:
model = CNN(784, 784, 10)
model.state_dict()

OrderedDict([('linear1.weight',
              tensor([[ 0.0251,  0.0062,  0.0101,  ...,  0.0188, -0.0095, -0.0332],
                      [ 0.0151,  0.0355,  0.0084,  ..., -0.0145,  0.0205,  0.0240],
                      [ 0.0170,  0.0166, -0.0217,  ...,  0.0025, -0.0139, -0.0276],
                      ...,
                      [ 0.0199,  0.0177,  0.0274,  ...,  0.0062,  0.0199,  0.0199],
                      [-0.0350,  0.0019, -0.0199,  ...,  0.0112,  0.0065, -0.0114],
                      [ 0.0110, -0.0117, -0.0100,  ...,  0.0099, -0.0130, -0.0340]])),
             ('linear1.bias',
              tensor([-1.5012e-02, -1.1462e-02, -1.2032e-02, -1.0899e-02, -2.6301e-02,
                       2.2232e-02,  2.7766e-02, -1.8248e-02,  3.3308e-02, -8.3576e-03,
                       1.9050e-02, -2.3517e-03, -3.1611e-02, -2.4826e-02,  1.9910e-02,
                      -1.8330e-02, -2.3731e-02, -2.1301e-02, -1.7307e-03,  3.2571e-02,
                      -7.0669e-03,  3.9649e-03, -1.3686e

In [127]:
# function for training the CNN 
# step means to upgrade the parameters
# backward means to take derivative
def train(Y, X, model, optimizer, criterion, epochs):
    cost = []
    total = 0
    for epoch in range(epochs):
        total = 0
        for y, x in zip(Y, X):
            yhat = model(x)
            loss = criterion(yhat, y)
            loss.backward()
            optimizer.step()
            optimizer.zero_grad()
            total += loss.item()
        cost.append(total)
    return cost

In [147]:
criterion = nn.MSELoss()
optimizer = torch.optim.SGD(model.parameters(),lr=0.01)
epochs =1
cost = train(Y, X, model, optimizer, criterion, epochs)

C:\Users\krish\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\torch\nn\modules\loss.py:536: UserWarning: Using a target size (torch.Size([])) that is different to the input size (torch.Size([10])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)


In [153]:
# saving a model 
PATH = './cifar_net.pth'
dict = model.state_dict()
torch.save(dict, PATH)
model.state_dict()

#net.load_state_dict(torch.load(PATH)) 
# can be used to load that model again

OrderedDict([('linear1.weight',
              tensor([[ 0.0251,  0.0062,  0.0101,  ...,  0.0188, -0.0095, -0.0332],
                      [ 0.0151,  0.0355,  0.0084,  ..., -0.0145,  0.0205,  0.0240],
                      [ 0.0170,  0.0166, -0.0217,  ...,  0.0025, -0.0139, -0.0276],
                      ...,
                      [ 0.0199,  0.0177,  0.0274,  ...,  0.0062,  0.0199,  0.0199],
                      [-0.0350,  0.0019, -0.0199,  ...,  0.0112,  0.0065, -0.0114],
                      [ 0.0110, -0.0117, -0.0100,  ...,  0.0099, -0.0130, -0.0340]])),
             ('linear1.bias',
              tensor([-1.5629e-02, -1.0885e-02, -1.2238e-02, -1.1085e-02, -2.5370e-02,
                       2.2481e-02,  2.8009e-02, -1.9097e-02,  3.2363e-02, -9.1916e-03,
                       1.9301e-02, -1.2365e-03, -3.0601e-02, -2.4277e-02,  1.4513e-02,
                      -1.7841e-02, -2.4134e-02, -2.2448e-02, -9.5263e-04,  3.3421e-02,
                      -7.2307e-03,  3.1001e-03, -1.2482e

In [154]:
mnist_data_test = pd.read_csv('mnist_train.csv', dtype="float").dropna()
Y_test = torch.tensor(mnist_data_test['label']).float()
X_list = mnist_data_test.drop(columns=['label'])
X_test = torch.tensor(X_list.values).float()